version: '3.9'
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD
      MYSQL_USER: user 
      MYSQL_PASSWORD: PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      - docker-microservices

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - docker-microservices

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - docker-microservices
  kong:
    image: kong:latest
    container_name: kong-gateway
    restart: unless-stopped

    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/usr/local/kong/declarative/kong.yml"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
      KONG_PROXY_LISTEN: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
      KONG_LOG_LEVEL: "debug"
      KONG_PLUGINS: "bundled,custom-auth"
      KONG_LUA_PACKAGE_PATH: "/usr/local/share/lua/5.1/?.lua;;"
      KONG_DECLARATIVE_CONFIG_STRING: "{}"
      KONG_NGINX_WORKER_PROCESSES: "1"
      KONG_NGINX_DAEMON: "off"
      # You can skip KONG_NGINX_USER for container safety
       # 🔹 Add a 10MB shared dictionary for rate limiting
      KONG_NGINX_HTTP_LUA_SHARED_DICT: "user_rate_limit 10m"

    networks:
      - docker-microservices

    volumes:
      - ./kong-config/kong/custom-plugins/custom-auth/handler.lua:/usr/local/share/lua/5.1/kong/plugins/custom-auth/handler.lua
      - ./kong-config/kong/custom-plugins/custom-auth/schema.lua:/usr/local/share/lua/5.1/kong/plugins/custom-auth/schema.lua
      - ./kong-config/kong/config/kong.yml:/usr/local/kong/declarative/kong.yml

    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"

volumes:
  mysql-db:
    driver: local

networks:
  docker-microservices:
    driver: bridge
