version: "3.9"

services:
  auth-service:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "9898:9898"
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: authservice
      MYSQL_USER: root
      MYSQL_PASSWORD: PASSWORD
    networks:
      - docker-microservices

  ds-service:
    build:
      context: ./DataScienceService/dsService
      dockerfile: Dockerfile
    container_name: ds-service
    ports:
      - "8010:8010"
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      OPENAI_API_KEY: <Your API key here> 
    networks:
      - docker-microservices

  expense-service:
    build:
      context: ./ExpenseService
      dockerfile: Dockerfile
    container_name: expense-service
    ports:
      - "9899:9898"
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: expenseservice
      MYSQL_USER: root
      MYSQL_PASSWORD: PASSWORD
    networks:
      - docker-microservices

  user-service:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "9810:9810"
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: userservice
      MYSQL_USER: root
      MYSQL_PASSWORD: PASSWORD
    networks:
      - docker-microservices

networks:
  docker-microservices:
    driver: bridge
